name = "watch"
compatibility_date = "2026-06-04"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://oqpjuhtatyxufksgymqt.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_piY_1ttbqtN1bEjDBRxJyA_bnCOWbhf"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "watch"
