name = "watch"
main = ".open-next/worker.js"
compatibility_date = "2026-06-04"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "watch"
